/* cis_keys.h - Pinned CIS trust anchors.
 *
 * GENERATED by tools/cis_keygen.py.  Hand edits survive only until the next
 * regeneration, so the tool is the supported way to change this file.
 *
 * This file composes two independent things into the one table cis_core.c walks:
 *
 *   OW_CIS_PROVISIONED_KEYS_INITIALISER  real anchors, added by `provision`
 *   OW_CIS_DEV_KEYS_INITIALISER          the dev anchor, added by CIS_DEV_TRUST
 *
 * The split matters because the two have different provenance.  A provisioned
 * anchor comes from a private key held off the build machine.  The dev anchor
 * comes from a seed printed in tools/cis_block.py, so trusting it means trusting
 * anyone with a checkout of this repository.  Keeping them in separate macros is
 * what makes that distinction reviewable in the table rather than only in prose:
 * a build can carry the second and not the first.
 *
 * Only the public half of any key is ever written here.  A private key is an
 * input to `provision` and to nothing else; it is not copied into this
 * repository, not embedded in any image, and does not exist on the target. */
#ifndef OW_CIS_KEYS_H
#define OW_CIS_KEYS_H

#include <stdint.h>

/* Bounds check applied before CIS spends time hashing: an image larger than
 * this is refused unmeasured rather than measured and then rejected. */
#define OW_CIS_DEFAULT_MAX_IMAGE_SIZE 0x00400000u /* 4 MiB */

typedef struct {
    const char* Name;
    uint8_t     KeyId[16];
    uint8_t     PublicKey[32];
    uint32_t    Flags;
} ow_cis_pinned_key_t;

/* No provisioned anchors.  An OpenWindows build with an empty trust store
 * refuses every image, which is the intended default: a machine that will not
 * run unreviewed code rather than a machine that runs whatever it finds. */
#define OW_CIS_PROVISIONED_KEY_COUNT 0u
#define OW_CIS_PROVISIONED_KEYS_INITIALISER

#include "cis_keys_dev.h"

/* Everything cis_core.c installs at init. */
#define OW_CIS_PINNED_KEY_COUNT \
    (OW_CIS_PROVISIONED_KEY_COUNT + OW_CIS_DEV_KEY_COUNT)

/* The table is always defined, even when empty, so that code which indexes it
 * inside a count-bounded loop still compiles against an unprovisioned build.
 * OW_CIS_PINNED_KEY_COUNT, not this size, is what bounds every lookup. */
#define OW_CIS_KEY_TABLE_SIZE \
    (OW_CIS_PINNED_KEY_COUNT > 0u ? OW_CIS_PINNED_KEY_COUNT : 1u)

static const ow_cis_pinned_key_t OW_CIS_PINNED_KEYS[OW_CIS_KEY_TABLE_SIZE] = {
    OW_CIS_PROVISIONED_KEYS_INITIALISER
    OW_CIS_DEV_KEYS_INITIALISER
};

#endif /* OW_CIS_KEYS_H */
