/* cis_keys_dev.h - the opt-in development image anchor.
 *
 * GENERATED by tools/cis_keygen.py emit-dev.  The seed it names is
 * DEV_IMAGE_SEED in tools/cis_block.py and is public: it is in the repository,
 * so anyone who can build this tree can sign an image this file's anchor trusts.
 *
 * That is the whole point and also the whole danger.  It exists so a development
 * build can boot an image it signed itself, and it is compiled in ONLY when the
 * build passes CIS_DEV_TRUST:
 *
 *   make qemu CIS_DEV_TRUST=1
 *
 * A build without that opt-in expands this file to nothing, which means it has no
 * dev anchor, which means it refuses every dev-signed image.  That is why the
 * guard is here rather than in cis_keys.h: the count has to be able to be zero
 * from a compile-time decision alone, with no runtime switch that a running
 * kernel could be talked out of.
 *
 * The flags are RELEASE | RECOVERY | TEST_ONLY.  RELEASE and RECOVERY are what
 * let the key sign boot and recovery images at all; TEST_ONLY is what marks it
 * as non-production for anything reading the store back.  Authority lives in the
 * trust store rather than in a special case in cis_verify.c on purpose -- see
 * cmd_emit_dev.
 *
 * A build containing this anchor will execute any image signed with the dev
 * seed.  Do not ship one. */
#ifndef OW_CIS_KEYS_DEV_H
#define OW_CIS_KEYS_DEV_H

#ifdef CIS_DEV_TRUST

#define OW_CIS_DEV_KEY_COUNT 1u
#define OW_CIS_DEV_KEYS_INITIALISER \
    { "dev", \
      { 0xA7, 0xC8, 0xB1, 0xA3, 0xF3, 0x9F, 0xC9, 0x9D, \
      0xD1, 0x89, 0x3A, 0x75, 0x0F, 0xE5, 0x0D, 0x96 }, \
      { 0x03, 0x6C, 0x5D, 0xA3, 0x26, 0xB1, 0x28, 0xF6, \
      0xE7, 0x2C, 0x65, 0xDF, 0x4F, 0xD8, 0x11, 0xBE, \
      0x2D, 0xA8, 0xFA, 0x22, 0x01, 0x44, 0x0F, 0x87, \
      0xE2, 0x34, 0xC5, 0x9D, 0x7F, 0x8F, 0x0C, 0x69 }, \
      0x00000007u }

#else /* !CIS_DEV_TRUST */

#define OW_CIS_DEV_KEY_COUNT 0u
#define OW_CIS_DEV_KEYS_INITIALISER

#endif /* CIS_DEV_TRUST */

#endif /* OW_CIS_KEYS_DEV_H */
