/* kprov_seed.c - kernel-provenance regression seed (test-only).
 *
 * The QEMU provenance regression (make qemu-provenance) boots the real kernel
 * with a signed openwinkrnl.owx embedded in the image and its matching
 * openwinkrnl.chk provisioned beside it, so the wired pre-init check
 * (OwSentinelVerifyKernelProvenanceFromVolume) runs against a known artifact
 * instead of against whatever happens to be on the volume.
 *
 * Two binaries are built from this one source.  They are byte-identical except
 * for the embedded header named on the include line:
 *
 *   control  - CORE_KERNEL / GPL-3.0-or-later, must be trusted and boot on;
 *   denied   - CORE_KERNEL / Apache-2.0, a licence the CORE_KERNEL policy
 *              refuses, must halt at the CIS policy check.
 *
 * The include is resolved from -I, not written literally, so the two cases can
 * share one source: the Makefile puts a different kprov_image.h on the include
 * path for each object.  Nothing here chooses a case at run time; the choice is
 * the link line, which is where the other seed objects put it too.
 *
 * This object provides the strong OwDiskSeedTestChk hook (the weak default is
 * in storage/owdisk.c) and is linked IN PLACE OF boot/owchk_seed.o, which
 * defines the same symbol.  They cannot both be linked, and they should not be:
 * the checksum file has to describe the kernel image this same object
 * provisions, so emitting the two from one place is what keeps them from
 * drifting apart.
 *
 * The checksum is computed at boot from the embedded bytes with the kernel's
 * own SHA-256, so "the chk matches the image" is true by construction rather
 * than by a build-time hash and a run-time hash agreeing.  The checksum is not
 * the property under test here -- both cases are expected to pass it -- it is
 * what isolates the provenance/licence decision, which is. */
#include "../inc/ow_types.h"
#include "../inc/ow_kprintf.h"
#include "../inc/ow_sentinel.h"
#include "../inc/ow_sha256.h"
#include "../storage/owdisk.h"
#include <stdint.h>
#include <stdbool.h>

/* Generated by tools/embed_owx.py from the case's packed .owx.  Defined here to
 * keep the name visible at the point of use; the implementation never needs to
 * know which licence is baked into it. */
#include "kprov_image.h"

bool OwDiskSeedTestChk(void) {
    uint8_t  digest[OW_SHA256_DIGEST_SIZE];
    char     hex[OW_SHA256_HEX_SIZE];
    uint32_t chk_ino = 0;
    OW_STATUS st;

    ow_sha256(g_kprov_image, (size_t)KPROV_IMAGE_SIZE, digest);
    ow_sha256_to_hex(digest, hex);

    /* openwinkrnl.chk: 64 lowercase hex digits and nothing that the sentinel's
     * scanner would treat as a separator, exactly as tools/owx_pack.py emits. */
    st = OwFsOwfsCreate(OW_KERNEL_CHK_NAME, &chk_ino);
    if (st == OW_SUCCESS) {
        st = OwFsOwfsWrite(OW_KERNEL_CHK_NAME, (const uint8_t*)hex,
                           (uint32_t)(OW_SHA256_HEX_SIZE - 1U));
    }
    if (st == OW_SUCCESS) {
        uint32_t img_ino = 0;
        st = OwFsOwfsCreate(OW_KERNEL_IMG_NAME, &img_ino);
        if (st == OW_SUCCESS) {
            st = OwFsOwfsWrite(OW_KERNEL_IMG_NAME,
                               (const uint8_t*)g_kprov_image,
                               (uint32_t)KPROV_IMAGE_SIZE);
        }
    }

    if (st == OW_SUCCESS) {
        ow_kprintf("[KPROV] test volume: seeded %s (%u bytes) + matching %s\r\n",
                   OW_KERNEL_IMG_NAME, (unsigned)KPROV_IMAGE_SIZE,
                   OW_KERNEL_CHK_NAME);
        return true;
    }
    ow_kprintf("[KPROV] test volume: provenance fixture seed FAILED (code 0x%X)\r\n",
               (unsigned)st);
    return false;
}
