#!/usr/bin/env python3
"""Emit a C byte-array header from a packed OWX1 image.

Used to bake userspace executables into the kernel image, so that a test image
can provision a freshly formatted RAM volume at boot.  There is one of these per
userspace image -- owinit, owinitv, owrs -- and each call names the symbols it
wants, so the generated headers cannot collide and nothing has to be renamed by
hand at the include site.

Two input modes:

  --no-pack   The input is already a packed OWX1 file.  Used for the images this
              repository builds itself (the emergency pair), where the Makefile
              has already run tools/owx_pack.py as a separate, visible step.

  (default)   The input is a PE image and is packed here, with --subsystem.  Used
              for owinit, which is produced by OpenWindows-Essentials and arrives
              as a PE wearing an .owx name.
"""
import argparse
import pathlib
import subprocess
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("input")
    parser.add_argument("output")
    parser.add_argument("--packer", default="tools/owx_pack.py",
                        help="packer used unless --no-pack is given")
    parser.add_argument("--no-pack", action="store_true",
                        help="treat the input as an already-packed OWX1 image")
    parser.add_argument("--subsystem", default="0x04",
                        help="OWX1 subsystem byte (default 0x04, boot)")
    parser.add_argument("--symbol", required=True,
                        help="name of the generated byte array")
    parser.add_argument("--size-macro", required=True,
                        help="name of the generated length macro")
    parser.add_argument("--guard", required=True,
                        help="include guard for the generated header")
    parser.add_argument("--note", default="",
                        help="leading comment describing the image's origin")
    args = parser.parse_args()

    input_path = pathlib.Path(args.input)
    output_path = pathlib.Path(args.output)
    if not input_path.is_file():
        raise SystemExit(f"missing input: {input_path}")

    if args.no_pack:
        data = input_path.read_bytes()
    else:
        packaged = output_path.with_suffix(".owx")
        subprocess.run(
            [sys.executable, args.packer, str(input_path), str(packaged),
             "--subsystem", args.subsystem],
            check=True,
        )
        data = packaged.read_bytes()

    if not data:
        raise SystemExit(f"refusing to emit an empty image header: {input_path}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="ascii", newline="\n") as header:
        if args.note:
            header.write(f"/* {args.note} */\n")
        else:
            header.write(f"/* Generated from {input_path}. */\n")
        header.write(f"#ifndef {args.guard}\n#define {args.guard}\n")
        header.write(f"#define {args.size_macro} {len(data)}U\n")
        header.write(f"static const unsigned char {args.symbol}[] = {{\n")
        for offset in range(0, len(data), 12):
            row = ", ".join(f"0x{byte:02X}" for byte in data[offset:offset + 12])
            header.write(f"    {row},\n")
        header.write("};\n#endif\n")


if __name__ == "__main__":
    main()
